### ISSUE TITLE
wishlist: #vars (or similar) to show current variables

### ISSUE THREAD

**Issue by garu** [doy/reply#39]
Hi doy! Thanks a lot for Reply - it's really cool :)

I was wondering if there is a way to see a list of all the variables currently available in the REPL. Specifically, I mean the ones created via my/our/state by the user.

Right now the only way I know how to do it is by either peeking at the history or having tab completion on and doing $a[tab], $b[tab] etc, but it does expand to other stuff as well.

For example:

```
> my $foo = 42
> my @meep = qw( some values )
> my $schema = My::Schema->connect( "..." );
> #vars
$foo
@meep
$schema
```
Ideally, it would show values as well, but it doesn't have to be that fancy (specially since values can be huge, and the user can just type "@meep" anyway after "#vars" to see its content anyway)

Would this fit into your vision for Reply?

**Comment by doy** [comment]
Done in 0.41.
