### ISSUE TITLE
ReadLine plugin can't handle quoted paths, but the pod implies it can

### ISSUE THREAD

**Issue by y** [doy/reply#49]
(I commented in #48 about this, but I'm guessing you didn't see it because the ticket was closed at that point.)
The pod example shows shows the `history_file` option can take a quoted path, but that is actually not the case.
This works: `history_file = ~/.reply_history`
This doesn't: `history_file = '~/.reply_history'`.
If you use `$history = glob($history)` instead of `$history =~ s{^~/}{$ENV{HOME}/}` it will properly deal with the quotes, though it might be better dealing with them at the config reader level.

**Comment by doy** [comment]
I just changed the documentation in version 0.40 to stop indicating that quotes are allowed - I don't really have the motivation to change how the config file parser works at the moment.
