### ISSUE TITLE
Bare heredoc

### ISSUE THREAD

**Issue by vickenty** [doy/reply#51]
I tried to use a bare heredoc in the repl session and something amazing happened:

```
1> my $x = <<
Use of bare << to mean <<"" is deprecated at reply input line 1.
Use of uninitialized value $^WARNING_BITS in concatenation (.) or string at reply input line 1.
$res[0] = ';
BEGIN {
    201330658 = 256;
    HASH(0xd2fe70) = %^H;
    UUUUUUUUUUUUUUUUU = ;
}
'
```

**Comment by doy** [comment]
Dup of #50 (the output is maybe surprising, but I don't think it's worth doing something hacky about it, since it doesn't particularly harm anything).
